name: '이슈 생성'
description: 'Repo에 이슈를 생성하며, 생성된 이슈는 Jira와 연동됩니다.'
title: '이슈 이름을 작성해주세요'
body:
  - type: input
    id: parentKey
    attributes:
      label: '🎟️ 상위 작업 (Ticket Number)'
      description: '상위 작업의 Ticket Number를 기입해주세요'
      placeholder: 'SKP-00'
    validations:
      required: true

  - type: input
    id: branch
    attributes:
      label: '🌳 브랜치명 (Branch)'
      description: '작업에 사용할 브랜치명을 영어로 입력해주세요.'
      placeholder: 'feature/your-branch-name'
    validations:
      required: true
      
  - type: input
    id: description
    attributes:
      label: '📝 상세 내용(Description)'
      description: '이슈에 대해서 간략히 설명해주세요'
      placeholder: |
        - 어떤 작업인지
        - 무엇을 목표로 하는지
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: '✅ 체크리스트(Tasks)'
      description: '이슈 해결을 위한 작업 목록을 체크박스로 작성해주세요.'
      value: |
        - [ ] 작업 1
        - [ ] 작업 2
    validations:
      required: false
