name: 'PR 생성'
description: 'PR을 생성하며, 관련 이슈와 Jira 연동 정보를 포함합니다.'
title: '[Feat] 간단한 PR 제목'
body:
  - type: input
    id: issueNumber
    attributes:
      label: '🔗 관련 이슈 번호'
      description: '이 PR과 연결될 이슈 번호를 입력해주세요 (예: #12)'
      placeholder: '#이슈번호'
    validations:
      required: true

  - type: input
    id: branch
    attributes:
      label: '🌳 브랜치명'
      description: '기능이 개발된 브랜치명을 입력해주세요'
      placeholder: 'feature/login-page'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: '📋 설명'
      description: '이 PR에서 어떤 변경이 이루어졌는지 작성해주세요'
      placeholder: |
        - 로그인 API 연동
        - 로그인 실패 시 에러 메시지 추가

  - type: textarea
    id: checklist
    attributes:
      label: '✅ 작업 체크리스트'
      description: '모든 작업을 완료했는지 확인해주세요'
      value: |
        - [ ] 코드 작성
        - [ ] 테스트 완료
        - [ ] 코드 리뷰 반영
        - [ ] 문서화
    validations:
      required: true
